### ISSUE TITLE
modal not centered

### ISSUE THREAD

**Issue by mandricmihai** [HTMLGuyLLC/jAlert#11]
![ddssd](https://cloud.githubusercontent.com/assets/5292321/8637117/7fdac672-288a-11e5-84e4-13501eb35b42.png)
The first line of the source page are those

``` html
NULL
<!DOCTYPE html>

<html class="no-js" lang="en-US">
<head>
```

null is from the php code
If I delete that null everything is centered but with that null before the doctype is not centered anymore

**Comment by HTMLGuyLLC** [comment]
Lol i couldn't tell you why having invalid html ruins the centering, but I can tell you that's invalid html. Lol

**Comment by VersatilityWerks** [comment]
*having

**Comment by HTMLGuyLLC** [comment]
BTW, I don't know if you have any need for it, but jTimeout goes well with jAlert:
http://flwebsites.biz/jTimeout/

**Comment by mandricmihai** [comment]
Not needing but looks great :+1: but who knows when I might need it :smiley:

**Comment by HTMLGuyLLC** [comment]
Cool, it's there for you when you do.

**Comment by duduironeagle** [comment]
Hello! I managed to solve this problem . Do the following:

Edit the jAlert-v3.js file on line 262 put like this: 
`var viewportHeight = Math.ceil (screen.height),`

this solves the modal centering problem when a lot of information are displayed on the screen!

**Comment by HTMLGuyLLC** [comment]
@duduironeagle  - Can you make this change and do a pull request?

**Comment by duduironeagle** [comment]
I did not understand what you mean

**Comment by duduironeagle** [comment]
@VersatilityWerks - I did not understand what you mean

**Comment by HTMLGuyLLC** [comment]
Can you create a branch, make the change, and submit a pull request? That way I can just add your changes and you get credit for contributing to the repo?

**Comment by duduironeagle** [comment]
I do not know how to do it. Feel free to do what has to be done . I do not require credit.

**Comment by duduironeagle** [comment]
@VersatilityWerks - I do not know how to do it. Feel free to do what has to be done . I do not require credit.
