### ISSUE TITLE
the confirmation box doesn't close on click anywhere

### ISSUE THREAD

**Issue by mandricmihai** [HTMLGuyLLC/jAlert#12]
the confirmation box doesn't close on click anywhere

**Comment by HTMLGuyLLC** [comment]
I changed the way this functions slightly kind of recently and it works fine for me in chrome. So either a) You have a cached version of the javascript and it's working fine or b) You're using a browser I never tested in. What browser/operating system? If you hold the shift button and click refresh next to the URL, does it fix the problem?

**Comment by mandricmihai** [comment]
I have google chrome 43.0.2357.132 m windows 10 tehnical preview but it's working on simple successAlert or errorAlert  but not on confirmation

**Comment by HTMLGuyLLC** [comment]
Oh that's why. Yea, confirmation disables it. It's not smart enough to know if you clicked the background or the alert itself, so to prevent it from closing before you get to click the yes or no, it's disabled. This isn't really an issue, but it's not a bad idea for an enhancement. I'll consider adding it to the next version.

**Comment by HTMLGuyLLC** [comment]
Sorry I didn't read the title close enough. I see you did specify confirmation box.

**Comment by wilmarmacosta** [comment]
I made a 2 changes to fix this issue:

First, disable the following script at line 115 which prevents the alert box to close

/\* If there are button(s), then you obviously don't want to hide the div when you alert anywhere or they'll be useless...SAME with autofocus */
        //if ((typeof alert.options.btns == 'object' || typeof alert.options.btns == 'array') || alert.options.autofocus) {
            //alert.options.closeOnClick = false;
        //}

Secondly, the alert box should only close when clicked outside, so to fix that, change the script at line :

/\* Mouseup on document */
    $.fn.jAlert.onMouseUp = function(e){

```
    /* Find top visible jAlert and see if it has closeOnClick enabled */
    var lastVisibleAlert = $('.jAlert:visible:last'); 

    if( lastVisibleAlert.options.closeOnClick )
    {
        //close only if clicked outside
        if (!$(event.target).is('.jAlert *')) {
            lastVisibleAlert.closeAlert();
        }
    }

}; 
```

I hope this helps. 

This plugin is awesome. Thanks VersatilityWerks...

**Comment by HTMLGuyLLC** [comment]
Your contributions are appreciated. I will take them into consideration for the next version. The only thing I want to do is make sure what you're suggesting is cross-browser compatible.

**Comment by HTMLGuyLLC** [comment]
I will look at adding this this weekend.

**Comment by HTMLGuyLLC** [comment]
Fixed in the latest version. Thanks again!
