### ISSUE TITLE
IE 10 & iframe option

### ISSUE THREAD

**Issue by jaltek** [HTMLGuyLLC/jAlert#13]
Hi,

the iframe option of jAlert doesn't seem to work in Internet Explorer 10.
I also tried the example at http://flwebsites.biz/jAlert/.

**Comment by HTMLGuyLLC** [comment]
I'll test as soon as I can. Thank you for the heads up!

**Comment by jaltek** [comment]
Note: In contrast, Internet Explorer 11 works ;)

**Comment by HTMLGuyLLC** [comment]
Thank you for the additional details! :)

**Comment by HTMLGuyLLC** [comment]
I'm at work and don't have access to IE10, I pushed a possible fix. Can you please test it?

**Comment by jaltek** [comment]
Perfect! That fixed it. Thanks for the quick fix ;)

**Comment by HTMLGuyLLC** [comment]
Awesome!
