### ISSUE TITLE
Where do you use jAlert? POST YOUR URL!

### ISSUE THREAD

**Issue by HTMLGuyLLC** [HTMLGuyLLC/jAlert#15]
It would be cool if we had a list of public sites that use jAlert. Share yours below!

**Comment by Bluscream** [comment]
https://github.com/Bluscream/BetterDiscord-Plugins-and-Themes/blob/master/plugins/0_BetterAPI.js

**Comment by HTMLGuyLLC** [comment]
@Bluscream Your link is dead. Also, try the latest version!

**Comment by Bluscream** [comment]
> Bluscream  commented on Dec 16 2015

**Comment by HTMLGuyLLC** [comment]
I realize it was 7 months ago, I was just looking to keep this list up-to-date. It doesn't help anyone to have broken links in here. If you don't have a new one, can you remove it?
