### ISSUE TITLE
jAlert-functions.js giving the error TypeError: alert.each is not a function.

### ISSUE THREAD

**Issue by Wivison** [HTMLGuyLLC/jAlert#18]
I tried to use the jAlert-functions.js's own test page and I'm getting the error alert.each is not a function in line 30 of jAlert-v3.js. How to proceed? Thank you!

**Comment by HTMLGuyLLC** [comment]
I see. An effect of a recent change. Please test with the new version I just pushed.

**Comment by Wivison** [comment]
Now it's working. Thanks for the quick response.

**Comment by Crisf07** [comment]
sorry, I hope these captures serve
this is the div in the index
![div](https://cloud.githubusercontent.com/assets/14255495/9834808/7c9a771e-599a-11e5-995f-df3d730f8a30.PNG)
![links](https://cloud.githubusercontent.com/assets/14255495/9834809/7c9fd51a-599a-11e5-8a5e-1eaf1f535e2b.PNG)
![main](https://cloud.githubusercontent.com/assets/14255495/9834810/7ca22194-599a-11e5-9947-ff5593adffa1.PNG)
button "resgistrarse" is #reg_c
![pagina](https://cloud.githubusercontent.com/assets/14255495/9834811/7cab1024-599a-11e5-8386-db5106603deb.PNG)

**Comment by HTMLGuyLLC** [comment]
If you’re clicking reg_c before reg, then that would easily explain it. You don’t have jalert loaded yet.

I highly recommend you don’t use .load to include jalert and just put it in index.html.

Thank you,
- Shane S. 

Web-Developer
Versatility Werks
http://FLWebsites.biz http://flwebsites.biz/

Call me: 
   dial **verswerks

**Comment by HTMLGuyLLC** [comment]
can you send the files so I can test? The screenshots are awesome, but not enough to see what’s wrong.

Thank you,
- Shane S. 

Web-Developer
Versatility Werks
http://FLWebsites.biz http://flwebsites.biz/

Call me: 
   dial **verswerks

**Comment by crisfz** [comment]
Click in login then in "¿No estas registrado?", put some different in "clave" and "confirme clave" or don't select chekbox for the alert

Date: Sat, 12 Sep 2015 19:21:18 -0700
