### ISSUE TITLE
jAlert-functions.js giving the error Uncaught TypeError: $.jAlert is not a function

### ISSUE THREAD

**Issue by crisfz** [HTMLGuyLLC/jAlert#19]
The problem occurs when I load an external file (using .load ()) to index and try to use an alert or any Jalert-function

sorry if my English is bad

**Comment by HTMLGuyLLC** [comment]
Please post your code or something or I can't help.

**Comment by HTMLGuyLLC** [comment]
I can guarantee you're just missing something in your implementation. I personally just downloaded and used the plugin tonight lol.

**Comment by crisfz** [comment]
i click reg before reg_c (obviously) and the index have jalert too

**Comment by crisfz** [comment]
How I send files?

(i'm awful using github)

**Comment by HTMLGuyLLC** [comment]
Send to hey[at]verswerks[com]

Thank you,
- Shane S.

Web-Developer
Versatility Werks
http://FLWebsites.biz http://flwebsites.biz/

Call me:

   dial **verswerks

**Comment by crisfz** [comment]
did you find the error?

**Comment by HTMLGuyLLC** [comment]
Haven’t had time to look. I’m working on a project for someone and I need it done this weekend. I’ll get to it as soon as I can.

Thank you,
- Shane S. 

Web-Developer
Versatility Werks
http://FLWebsites.biz http://flwebsites.biz/

Call me: 
   dial **verswerks

**Comment by crisfz** [comment]
ok, i'll wait
