### ISSUE TITLE
how to call the yellow?

### ISSUE THREAD

**Issue by mandricmihai** [HTMLGuyLLC/jAlert#2]
for green we have succesAlert for red errorAlert for yellow it could be dangerAlert or infoAlert but I think danger is better you chose

**Comment by HTMLGuyLLC** [comment]
Ah, you want a shortcut function. That's cool. I'll make one for each real quick.

**Comment by mandricmihai** [comment]
Thanks :smiley:

**Comment by HTMLGuyLLC** [comment]
The full way of calling it would be like this:
$.jAlert({
'title': 'Hi',
'content':'what up',
'theme': 'yellow'
});

**Comment by mandricmihai** [comment]
Btw how to disable the animation on the shortcut function?Is there something like a config for all the shortcut function?

**Comment by HTMLGuyLLC** [comment]
There is no way to disable the animation. You can override the default and set it to something else if you'd like. Such as a simple fade by using:
$.fn.jAlert.defaults.showAnimation = 'fadeIn';
$.fn.jAlert.defaults.hideAnimation = 'fadeOut';

**Comment by HTMLGuyLLC** [comment]
https://github.com/VersatilityWerks/jAlert/commit/169a76239b4f9beac2e80de4b28e3ec4bf503f24
