### ISSUE TITLE
Line breaks not working in jAlerts.

### ISSUE THREAD

**Issue by Bluscream** [HTMLGuyLLC/jAlert#22]
I can't use line breaks in a alert. Thats sad :c 

![s](https://i.gyazo.com/fe6d8d8e1391443a8169c649af1438c1.png)

``` js
infoAlert("\""+ username +"\"s Info","Name: "+username+"\\n"+"\n"+"ID: " + id);
```

**Comment by Bluscream** [comment]
Also

``` js
$.jAlert({
    'title': username +'\'s Info',
    'content': 'Name: '+username+'\n'+'UID: '+id,
    'theme': 'blue',
    'size': 'md',
    'showAnimation': 'fadeInUp',
    'hideAnimation': 'fadeOutDown' 
});
```

Does not work.

**Comment by HTMLGuyLLC** [comment]
You can. This is HTML. Just use 

``` js
<br>
```

**Comment by Bluscream** [comment]
OMG thanks ^^ You should mention that somewhere ^^

Cause https://www.google.de/search?q=jalert+multiline+alerts and
https://www.google.de/search?q=jalert+linebreak bring confusing results :)

**Comment by HTMLGuyLLC** [comment]
There's a big difference between a plain javascript alert and my plugin. Javascript alerts using the plain alert() function require \n for new lines because they don't show HTML as-is. My alert is a simple div and whatever content you enter will be rendered as normal HTML is.

**Comment by Bluscream** [comment]
So i could even use a `<table>` inside of it? :D

**Comment by HTMLGuyLLC** [comment]
Lol yes.
