### ISSUE TITLE
When I'm watching a jAlert in my web, and I press space key...

### ISSUE THREAD

**Issue by JesusGarrobo** [HTMLGuyLLC/jAlert#25]
... the same message shows in a new jAlert. This new jAlert was showing over the first jAlert. Why? In the demo version don't happend this...

**Comment by HTMLGuyLLC** [comment]
Lol..you realized that the button beneath still had focus and hitting space activated it or something?

**Comment by HTMLGuyLLC** [comment]
I changed it to remove focus from whatever is focused on open.
