### ISSUE TITLE
How to use direct link Youtube ? 

### ISSUE THREAD

**Issue by loorlab** [HTMLGuyLLC/jAlert#26]
Hi , for our function we have the following code :

`$('.lb-video').alertOnClick({
            'video': 'https://www.youtube.com/embed/aVO2SKs9BK8',
            'size': 'lg'
    });`   

But want to use the direct link ( https://www.youtube.com/watch?v=aVO2SKs9BK8 ) without embed, is that possible? 

Thanks !

**Comment by HTMLGuyLLC** [comment]
Do you mean you want it to lead to the video on youtube on click of '.lb-video' or you want it to popup and show a link?

**Comment by HTMLGuyLLC** [comment]
To have '.lb-video' link to that video, you don't need jAlert. You just do an onclick handler with a window.location.href = 'VIDEO_URL';

**Comment by HTMLGuyLLC** [comment]
To have the link to youtube in a jalert, just use the content parameter

**Comment by loorlab** [comment]
It is that when we run the following code but the video does not load :

$('.lb-video').alertOnClick({ 'video': 'https://www.youtube.com/watch?v=aVO2SKs9BK8', 'size': 'lg' }); 

https://www.youtube.com/embed/aVO2SKs9BK8 vs https://www.youtube.com/watch?v=aVO2SKs9BK8

We do not need the direct link as a href, is the code that we show in this question jAlert .

**Comment by HTMLGuyLLC** [comment]
Oh Sorry, I see what you mean. The URL without /embed/, not the url to the video without embedding it. No, I do not believe that is possible.

**Comment by loorlab** [comment]
Please keep it as a suggestion for a future release, Thanks !
