### ISSUE TITLE
Is confirm waits for user input

### ISSUE THREAD

**Issue by Harshil12** [HTMLGuyLLC/jAlert#28]
Is this pluging waits until user action or it just execute the next line code in javascript ?

**Comment by HTMLGuyLLC** [comment]
Depends on how you implement it. If you put it directly in your on load function, it'll just run. If you wrap it in a button onclick handler, it'll wait.

**Comment by Harshil12** [comment]
Thanks for quick response,

I am integrating this confirm with some existing application in which after calling confirm it has return the code. If I am planning to move all code in handler then there is more code change.

Is there any way I can have something in JavaScript which can wait for user response.

Thanks,
Harshil

**Comment by HTMLGuyLLC** [comment]
I'm really not sure what you're asking, but if you can provide a code
sample, I might be able to help.

**Comment by HTMLGuyLLC** [comment]
Also, this isn't an issue with the code, but your implementation. So I'm closing.

**Comment by Harshil12** [comment]
Sorry,

I could not reply.

Yes this is not the issue with code but , I need help.

My problem is on my button there is two event written client side and server side.

on client side event java script function prepare the message and display into confirm box and then return true or false accordingly user action on confirm box , Based on true or false server side event fire.

Issue here is if I use this confirm box then it does not wait for user action and default retrun false so server side event does happen and save is not working. I am @ home once reach office will sent you a code base

Your help will save my lot of time.

Thanks in Advance,
