### ISSUE TITLE
Vertical scrollbar

### ISSUE THREAD

**Issue by mmucino1** [HTMLGuyLLC/jAlert#29]
When the jAlert window is displayed the vertical scrollbar disapear then when the jAlert window is closed the scrollbar doesn't appear again... is this the expected behavior?

**Comment by HTMLGuyLLC** [comment]
Doesn't appear again? In what browser?

**Comment by HTMLGuyLLC** [comment]
I read your message wrong and edited my response.

**Comment by mmucino1** [comment]
Chrome... this is the situation: a modal is opened, then I scroll to the bottom of the page then the top of the modal is hidden (normal) and if then I display an error message with jAlert plugin, the scrollbar dissapear but when the jAlert is closed there are not a scroll bar then I can't go back to the top of the modal... any idea why is this happening? Thanks in advance.

**Comment by HTMLGuyLLC** [comment]
Can you take a couple/few screenshots of the process? I can't recreate the issue you're having.

**Comment by mmucino1** [comment]
This screenshots are in order of the process: Thanks.
![uno](https://cloud.githubusercontent.com/assets/19369597/15713172/e94a9bd2-27da-11e6-811f-9f0b4fdc764a.png)
![dos](https://cloud.githubusercontent.com/assets/19369597/15713214/1731324a-27db-11e6-82ab-9a7b5a414960.png)
![tres](https://cloud.githubusercontent.com/assets/19369597/15713237/39a1dd66-27db-11e6-8470-5ec99ded4601.png)
![cuatro](https://cloud.githubusercontent.com/assets/19369597/15713255/53ea50ae-27db-11e6-81f1-fef3041f934e.png)

**Comment by HTMLGuyLLC** [comment]
Oh Ok, so you're using a Bootstrap Modal and it might be effecting the body overflow that jAlert messes with. I don't know if there is a fix to be honest...atleast not an immediately obvious one. I'll do my best to recreate and play with it to see what can be done.

**Comment by HTMLGuyLLC** [comment]
Thanks so much for the screenshots btw, huge help!
