### ISSUE TITLE
simple alert is not working

### ISSUE THREAD

**Issue by mandricmihai** [HTMLGuyLLC/jAlert#3]
alert("hi"); in console gives me the default alert and undefined in the console output.Everything else works.

**Comment by HTMLGuyLLC** [comment]
Interesting. Let me take a peek

**Comment by HTMLGuyLLC** [comment]
Oh...that's not an issue. There's no return value to the function so it shows undefined. If you called it from your code, you wouldn't get any warnings/errors.

**Comment by mandricmihai** [comment]
ah yes :smiley:

**Comment by HTMLGuyLLC** [comment]
Hey, just a heads up, I fixed a major body overflow: hidden; bug this weekend. You should download the latest version.

**Comment by mandricmihai** [comment]
I did like 6-5 hours a go thanks :smile:

**Comment by HTMLGuyLLC** [comment]
Haha good

**Comment by HTMLGuyLLC** [comment]
You should watch/star the repository so you can get updates.

**Comment by mandricmihai** [comment]
Yes good idea.Done.Thanks.

**Comment by HTMLGuyLLC** [comment]
NP
