### ISSUE TITLE
closeOnClick does not work on Safari / IOS

### ISSUE THREAD

**Issue by skyprimer** [HTMLGuyLLC/jAlert#30]
closeOnClick does not work in IOS. On android and browser no problem...

**Comment by skyprimer** [comment]
Solved by changing jalert-v4.js file line 646;

**from**
$(document).off('mouseup', $.fn.jAlert.onMouseUp);
$(document).on('mouseup', $.fn.jAlert.onMouseUp);

**to:**
$(document).off('touchstart', $.fn.jAlert.onMouseUp);
$(document).off('touchstart', $.fn.jAlert.onMouseUp);

**Comment by HTMLGuyLLC** [comment]
Good catch. The only thing I'd recommend is having both events. I'll get this added to master soon!

**Comment by HTMLGuyLLC** [comment]
Fixed in latest commit
