### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by lenamtl** [HTMLGuyLLC/jAlert#31]
Hi, do you have any plan to use it with Bootstrap?

**Comment by HTMLGuyLLC** [comment]
What do you mean? I use it on a few different Bootstrap sites.

**Comment by Rhend** [comment]
Works perfectly fine with Bootstrap but maybe Lenamtl want to know if you gonna integrate some bootstrap UI.

**Comment by HTMLGuyLLC** [comment]
So a CSS file to style it like Bootstrap's Modals? I could probably do that one day. I just don't have time at the moment.

**Comment by Rhend** [comment]
Yes and what's the point after all ? If we need a modal style we can use it already ^^

**Comment by HTMLGuyLLC** [comment]
True dat. I don't think it's worth the time.

**Comment by lenamtl** [comment]
It's just a suggestion...
