### ISSUE TITLE
Selectors in div

### ISSUE THREAD

**Issue by robyone67** [HTMLGuyLLC/jAlert#35]
Hello,
What happens to the #id Selector which are located in the div that are included in jAlert?
Let me explain: if in a div, such as the one with id = "fromDiv" you find in the sample file test.html, insert the following lines:

`<div id="test1">test1</div>`
`<form name="edit"><input type="text" name="test2" value="test2" size="5"></form>`
`<input type="button" onClick="document.getElementById('test1').innerHTML='ok'; document.edit['test2'].value='ok'" `value="test">`

Then if I press the "test" button should appear "ok" in the div "test1" and in the textbox,  instead  seems that these elements do not exist, and I get an error in the JavaScript console.

Note that if I remove the "display: none" from "fromdiv", and so this is always visible, the test is working properly.

When the "fromdiv" is included in jalert,  the selectors "disappear" ...

Can it be solved? Thank you.

**Comment by HTMLGuyLLC** [comment]
Please share more code. I fail to understand your scenario.

**Comment by robyone67** [comment]
This is an example, but the problem always occurs with selector included in the div displayed by jalert.
Do do various tests, I put inside the "fromDiv" a div,  a text box and a button.

`<a href="#" class="btn" data-jAlert data-title="From DIV" data-content="#fromDiv">Pulls Content From DIV</a>`
`<div id="fromDiv" style="display: none;">`
`<div id="test1">test1</div>`
`<form name="edit"><input type="text" name="test2" value="test2" size="5"></form>`
`<input type="button" onClick="document.getElementById('test1').innerHTML='ok'; document.edit['test2'].value='ok'" value="Click me">`
`</div>`
1. click on link "Pulls Content From DIV":  appears a jalert box
2. click on the button "Click me": instead of "test" terms should appear "ok". Nothing happens: the javascript console display "TypeError: Cannot set property 'value' of undefined", because the page can not find the selector "test1" and textbox "test2"

if instead I put directly the "fromDiv" into the HTML page and not in jalert, everything works fine.

**Comment by HTMLGuyLLC** [comment]
At least one issue here is you're defining an ID in the content (#test1) and when jAlert pops up, it doesn't remove the original element so there ends up being 2 elements with the same id. 

Although I still don't recommend using inline JS like that, I think using jQuery would handle some issues for you like cross-browser compatibility and live node changes. For instance, the following is working:

``` html
<a href="#" class="btn" data-jAlert data-title="From DIV" data-content="#fromDiv">Pulls Content From DIV</a>
<div id="fromDiv" style="display: none;">
<div class="test1">test1</div>
<form name="edit"><input type="text" name="test2" value="test2" size="5"></form>
<input type="button" onClick="$('.test1').text('ok'); $('input[name=test2]').val('ok');" value="Click me">
</div>
```

**Comment by HTMLGuyLLC** [comment]
I don't have the time to investigate further, but I assure you it's not an issue with the jAlert plugin. Good luck!
