### ISSUE TITLE
Close jAlert from iframe

### ISSUE THREAD

**Issue by robyone67** [HTMLGuyLLC/jAlert#36]
Hello,
if I display an iframe with jalert, how can i programmatically close the jalert box with a command in the page displayed by jalert?
In short, in the page displayed in the iframe, there must be a button that executes a command like 
`window.parent.jAlert.closeAlert()`
or something like that: what is the exact syntax?
Thank you.

**Comment by HTMLGuyLLC** [comment]
I don't really have time to help with implementation questions, but off the top of my head...I think you can create a method in the parent window like:

```javascript
function closeTopAlert()
{
   $.jAlert('current').closeAlert(); 
}
```

then call

```javascript
window.parent.closeTopAlert();
```
