### ISSUE TITLE
jAlert with iframe scrolls automatically

### ISSUE THREAD

**Issue by F-web** [HTMLGuyLLC/jAlert#39]
when I open jAlert with iframe then the page behind the jAlert scrolls to the top, is there a way to prevent this?

**Comment by HTMLGuyLLC** [comment]
Yes, it's because the 100% height is slightly too much and it changes the way the modal works. It's a small bug I've been meaning to fix but I haven't had time. If you want to fix it and do a pull request, that'd be great.

**Comment by HTMLGuyLLC** [comment]
Had a better version of this issue posted. Will close this and keep the other.
