### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by codigoart** [HTMLGuyLLC/jAlert#41]
browser: Microsoft Edge 38.14393.0.0
issue1: edge freeze when i resize to small win browser (you need to try dif small sizes some time it works depens on the size)
issue2: chrome version: 56.0.2924.87 chrome modal does not apper at top when very small window  
my code:
                    $.jAlert({
                        'ajax' : 'index.php?page=live&at=' + data.t,
                        'title': 'Reservation',
                        'content': 'Reservation',
                        'theme': 'black',
                        'size': 'auto',
                        'showAnimation': 'fadeInUp',
                        'hideAnimation': 'fadeOutDown',
                        'closeBtn' : false,
                        'closeOnEsc' : true,
                        fullscreen : false,
                        onclose : function(alert){$
                            clearInterval(refreshId); 
                            refreshId = setInterval(rotate, 5000);
                            return false; },
                        });

**Comment by HTMLGuyLLC** [comment]
Can you post a screenshot in chrome?

**Comment by codigoart** [comment]
im not using this anymore, the issue is modal instead of open at top when you are in mobilewinsize it opens at midle but when i resize the win it autofix the position to top

**Comment by HTMLGuyLLC** [comment]
Lol ok. No one else has stopped using it or reported this so I'm going to close the issue till it's documented better. Thanks. After reading your latest comment, I believe this is the functionality I added in order to ensure mobile users wouldn't have to scroll much.
