### ISSUE TITLE
Easy way to customize confirmation question

### ISSUE THREAD

**Issue by rafacompu** [HTMLGuyLLC/jAlert#42]
ToDo: 
~ Create a function to easily customize the confirmation question

**Comment by HTMLGuyLLC** [comment]
confirm(onconfirm, ondeny, confirmation_question, confirm_btn_text, deny_btn_text)
Just adding parameters to the confirm method should satisfy this.

**Comment by Yokomoko** [comment]
I don't think this works at all. Tried using confirm() and $jAlert with the confirmQuestion parameter, doesn't work, it always keeps 'Are you sure?'.

**Comment by HTMLGuyLLC** [comment]
Well, this issue is still open because I never added the question to the confirm method. That was just an example of how it could be modified to satisfy his request.

Using $.jAlert({ type: "confirm", confirmQuestion: "Whatever" }); does work.

**Comment by HTMLGuyLLC** [comment]
FYI, I recommend you use my jConfirm plugin. It pops up a tooltip right by the trigger element. Much faster for someone to use. https://github.com/HTMLGuyLLC/jConfirm

**Comment by HTMLGuyLLC** [comment]
Added confirm question as the third param for the confirm method in the latest release.

example:
```
confirm(function(){ alert('Confirmed'); }, function(){ alert('Not Confirmed'); }, 'What's up doc?');
```
