### ISSUE TITLE
btn href not functioning

### ISSUE THREAD

**Issue by 1nGlen** [HTMLGuyLLC/jAlert#44]
I have been unable to create buttons with working links. When the user clicks a button, the jAlert modal simply closes. I am using the btn href property as described in the documentation. Perhaps you could provide an example of a working btn href in Codepen?

**Comment by HTMLGuyLLC** [comment]
```
$.jAlert({
'title':'button',
btns: {'text':'Do not close', 'closeAlert':false, 'onClick': function(e){ e.preventDefault(); return false; } }
});
