### ISSUE TITLE
Disable the override of default alert

### ISSUE THREAD

**Issue by scott80109** [HTMLGuyLLC/jAlert#46]
Is there a way to disable the override of the default Javascript alert? I would like to keep the default alert box, but use jAlert for other scenarios.

**Comment by ChristianGabs** [comment]
Depend what you try to do ! I really don't completely understand what you try to do !

**Comment by scott80109** [comment]
If I write the code

`alert("Hello World");`

I want to see the default Javascript alert box with the "Ok" button to close, and not the jAlert themed popup with only the small "x" in the corner. I just introduced jAlert into a large project for use with the jTimeout plugin. I have hundreds, or thousands, of alerts in the code, and my client doesn't like the new jAlert alert format. I still want to use the standard Javascript alert with old alerts, and just use jAlert with the jTimeout tool.

**Comment by ChristianGabs** [comment]
EDIT : 

Sorry my mistake

/* Optional: Overwrites javascript's built-in alert function */
function alert(title, msg){
	if( typeof msg == 'undefined' )
	{
		msg = title;
		title = '';
	}
	$.jAlert({
		'title': title,
		'content': msg
	});
}

Remove this from jAlert-functions.js

After this will be remove then your alert will interact with **jquery alert**

**Comment by scott80109** [comment]
From the README for jAlert

```javascript
  alert('hi'); //override is enabled by default 
```
jAlert overrides the default Javascript alert, and it is enabled by default. I am looking for how to turn it off.

**Comment by ChristianGabs** [comment]
You must remove this from  jAlert-functions.js

This can not be turn off just remove it from the  jAlert-functions.js. This will not affect your jAlert if you remove it

If you look closer you don't realy need to use this ( jAlert-functions.js) this is just to help you but if you use only  jAlert.js you just need to call

$.jAlert

Example without jAlert-functions.js

$.jAlert({
  'title': 'Set It',
  'content': 'Set',
  'theme': 'green',
  'size': 'md',
  'showAnimation': 'fadeInUp',
  'hideAnimation': 'fadeOutDown'
});

So you can use both no problem but just remove the code I share with you

`/* Optional: Overwrites javascript's built-in alert function */
function alert(title, msg){
if( typeof msg == 'undefined' )
{
msg = title;
title = '';
}
$.jAlert({
'title': title,
'content': msg
});
}`

**Comment by scott80109** [comment]
That was it. Thank you. I was looking in the wrong file.

**Comment by ChristianGabs** [comment]
You welcome 😄

**Comment by HTMLGuyLLC** [comment]
Lol I'm a lil late now, but thanks for helping @ChristianGabs!
