### ISSUE TITLE
Can use multiple color fonts in alert

### ISSUE THREAD

**Issue by SethKitchen** [HTMLGuyLLC/jAlert#48]
I would like to pop a dialog up with a string of

red text, "YOU FAILED TO DO BLAH BLAH"

yellow text, "Im warning you to do blah blah"

green text, "you did this perfectly."

Can you add this enhancement?

**Comment by HTMLGuyLLC** [comment]
You can do this in your implementation. 

Just add CSS to your site like this:

```
.ja_green .ja_body
{
   color: green;
}

.ja_red .ja_body
{
   color: red;
}
........
```

Reference jAlert's CSS to find all the theme classes.
