### ISSUE TITLE
Doesn't work correctly in Lynx

### ISSUE THREAD

**Issue by mharris-Cb911** [HTMLGuyLLC/jAlert#50]
I'm trying to get this to work in the lynx browser but all it does is a whole lot of words on the page, can you help?

**Comment by shanecb911** [comment]
Codesmell

**Comment by shanecb911** [comment]
Good joke. Close this. lol.

**Comment by mharris-Cb911** [comment]
Oh wait, all my JS doesn't work in Lynx!  My bad.
