### ISSUE TITLE
Is it possible to accept an dom object as content?

### ISSUE THREAD

**Issue by KNVB** [HTMLGuyLLC/jAlert#53]
As title,Is it possible to accept an dom object as content?
It is because I need to add event handler for the content objects.

Besides that, an issue for noPadContent:true found, my code as the following:

`$.jAlert({
															noPadContent:true,
															'title': "Select a Directory",
															'content':msg,
															'theme': 'red',
															closeBtn:false,
															'btns': { 'text': 'Ok',class:"w3-red"}
														  });
`

where msg=&lt;div style=&quot;border:1px solid black;padding-top: 0px; margin-top: 0px;&quot;&gt;
  &lt;ul style=&quot;padding: 0px; margin: 0px;&quot;&gt;
    &lt;li style=&quot;margin-left: 10px; list-style: none;&quot;&gt;&lt;i class=&quot;fa fa-hdd-o&quot;&gt;&lt;/i&gt;&amp;nbsp;&lt;a rel=&quot;C:\&quot; style=&quot;cursor: pointer;&quot;&gt;C:\&lt;/a&gt;&lt;/li&gt;
    &lt;li style=&quot;margin-left: 10px; list-style: none;&quot;&gt;&lt;i class=&quot;fa fa-hdd-o&quot;&gt;&lt;/i&gt;&amp;nbsp;&lt;a rel=&quot;D:\&quot; style=&quot;cursor: pointer;&quot;&gt;D:\&lt;/a&gt;&lt;/li&gt;
    &lt;li style=&quot;margin-left: 10px; list-style: none;&quot;&gt;&lt;i class=&quot;fa fa-hdd-o&quot;&gt;&lt;/i&gt;&amp;nbsp;&lt;a rel=&quot;E:\&quot; style=&quot;cursor: pointer;&quot;&gt;E:\&lt;/a&gt;&lt;/li&gt;
    &lt;li style=&quot;margin-left: 10px; list-style: none;&quot;&gt;&lt;i class=&quot;fa fa-hdd-o&quot;&gt;&lt;/i&gt;&amp;nbsp;&lt;a rel=&quot;F:\&quot; style=&quot;cursor: pointer;&quot;&gt;F:\&lt;/a&gt;&lt;/li&gt;
    &lt;li style=&quot;margin-left: 10px; list-style: none;&quot;&gt;&lt;i class=&quot;fa fa-hdd-o&quot;&gt;&lt;/i&gt;&amp;nbsp;&lt;a rel=&quot;G:\&quot; style=&quot;cursor: pointer;&quot;&gt;G:\&lt;/a&gt;&lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;

The ok button row wider than bother content and title row.

**Comment by HTMLGuyLLC** [comment]
I considered this feature in the past. Next time I get to updating it, I will add. If someone else has a chance first, just open a pull request and I'll merge it.

**Comment by HTMLGuyLLC** [comment]
Latest version will automatically grab HTML of any dom element that is provided for the "content" property.
