### ISSUE TITLE
possible bug in javascript: viewportHeight

### ISSUE THREAD

**Issue by claudioimai** [HTMLGuyLLC/jAlert#59]
Just found this problem, in a window larger the the viewport, with a lightbox opening far below the viewport, rendering it useless. (in Firefox 59, at least)

I found this code on line 97:
```javascript
    var viewportHeight = $(window).height(),
    alertHeight    = alert.instance.height(),
    diff           = viewportHeight - alertHeight;
```

Fix:
 _$(window).height()_ returns the full height of the rendered page, while the code wants the viewport size.

I switched it to
```javascript
    var viewportHeight = window.innerHeight,
        alertHeight    = alert.instance.height(),
        diff           = viewportHeight - alertHeight;
````

window.innerHeight will correctly return the viewport height, thus positioning the window at the correct place.

**Comment by HTMLGuyLLC** [comment]
This is potentially a real fix, but I'd like someone to confirm browser compatibility before I merge.

**Comment by HTMLGuyLLC** [comment]
Latest version implements something like this. It was done to improve layout for larger alerts that are taller than the window which was causing them to be too close to the top of the window.
