### ISSUE TITLE
confirm method problem in firefox

### ISSUE THREAD

**Issue by mengdq** [HTMLGuyLLC/jAlert#64]
When I use confirm method in firefox, 
the following error occured.

DataCloneError: The object could not be cloned. prompt.js:138 

then denyBtn will not work.

btw, in chrome the error won't  happen.

**Comment by HTMLGuyLLC** [comment]
Thank you for reporting it. I will look now.

**Comment by HTMLGuyLLC** [comment]
Tested in Firefox on the demo page and it works fine?
<img width="1214" alt="screen shot 2018-10-24 at 7 32 54 am" src="https://user-images.githubusercontent.com/2415447/47427674-0c1ea500-d75f-11e8-97ff-52f82b116537.png">

**Comment by mengdq** [comment]
![jalert1](https://user-images.githubusercontent.com/13994707/47475181-61d57900-d855-11e8-95a8-8737e3441da4.PNG)

**Comment by mengdq** [comment]
As above,「No」button doesn't work

**Comment by mengdq** [comment]
It is a problem of my Firefox.

**Comment by HTMLGuyLLC** [comment]
Yea, your screenshot shows prompt.js is the issue, not jAlert.
