### ISSUE TITLE
How to know if alert is visible?

### ISSUE THREAD

**Issue by jfoclpf** [HTMLGuyLLC/jAlert#70]
After creating the alert
```js
var jAlertOnAppResume = $.jAlert({
        title: 'PDF digitalmente assinado?',
        content: 'Consegiu assinar o PDF com sucesso, fazendo uso da sua Chave Móvel Digital?',
        theme: 'dark_blue'
})
```

I can close it and open it with public methods `closeAlert` and `showAlert` but how do I know if the alert is closed/hidden or open/visible?

**Comment by HTMLGuyLLC** [comment]
Try `$.jAlert('current')` - It will return the currently open instance (if any)

**Comment by jfoclpf** [comment]
great, thanks
