### ISSUE TITLE
open link in new tab alert?

### ISSUE THREAD

**Issue by mandricmihai** [HTMLGuyLLC/jAlert#8]
Nice job with the videoAlert :+1:  . It's posible to add an open in new tab alert link?
Like this in html

``` html
<a href="http://google.ro" target="_blank"></a>
```

**Comment by HTMLGuyLLC** [comment]
Not sure what you mean. Can you try to rephrase your question? Also, just a heads up, I have a full-time job and won't be able to help you every day :P

**Comment by mandricmihai** [comment]
forget
found a new way thanks

**Comment by HTMLGuyLLC** [comment]
If the button is IN the jAlert popup using the jAlert btns param, you can use target.

Example:

``` javascript
$.jAlert({
'btns': { 'text': 'Go to google', 'target': '_blank', 'href': 'http://google.com' }
});
```
