### ISSUE TITLE
closeOnEsc removes all keydown events

### ISSUE THREAD

**Issue by jaltek** [HTMLGuyLLC/jAlert#9]
Hi,

by using the `closeOnEsc` option (which is true by default) previous keydown functions from **all** keys are removed. I think this is caused by 

```
$(document).off('keydown');
```

[jAlert-v3.js - Line 533](https://github.com/VersatilityWerks/jAlert/blob/master/src/jAlert-v3.js#L533)

IMHO only the function itself should be unregistered.

**Comment by HTMLGuyLLC** [comment]
Good point. If you'd like to fork and fix, I'll happily merge. Otherwise, I'll get to it when I get a chance.

**Comment by HTMLGuyLLC** [comment]
Fixed https://github.com/VersatilityWerks/jAlert/commit/b4bf16c6807056ee4795cf7fa9c7398b513dff9d

**Comment by jaltek** [comment]
Works like charm. Thx ;)

**Comment by HTMLGuyLLC** [comment]
Not a problem! Let me know if you need anything else :+1:
